### ISSUE TITLE
Force Atlas 3D for 0.9

### ISSUE THREAD

**Issue by mhebrard** [seinecle/Plugins-for-Gephi#29]
Hello, 
Is there a way to update Force Atlas 3D to work on gephi 0.9.x ? 
apparently the current version is still related to 0.8.x ...
thanks

**Comment by dkbohl** [comment]
I second that. Force Atlas 3D is one of my favorite layouts!

**Comment by seinecle** [comment]
I read that, sorry to be so slow, I have so many projects running at the
moment that I can't find the time to update my plugins... :( still, that's
on my list

**Comment by giovabal** [comment]
Any news?
I'd really like to see that happening.

**Comment by seinecle** [comment]
On its way! https://github.com/gephi/gephi-plugins/pull/143

**Comment by seinecle** [comment]
Note: Gephi 0.9 does not have the "sphere" nodes, that's a pity. So the network is shown in 3D, but it's not that cool. Still useful to get x y z coordinates though.

**Comment by barripdmx** [comment]
Hi,

Some solution for version 0.9.x?

**Comment by mb3152** [comment]
Any updates on this?

**Comment by DiegoUrbinaLum** [comment]
Is there any way to just calculate the X,Y,Z coordinates in Gephi 0.9.1 without actually plotting it? I have tried to install ForceAtlas3D, however, it does not work due to two plugins that are not supported in versions 0.9.x:

org_gephi.data.attributes.api
org_gephi.dynamic.api

Does anyone know a work around?

Thanks in advance.

Diego
